openapi: 3.0.0
info:
  title: Contoh API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Mengembalikan pesan sambutan
      responses:
        200:
          description: OK
          content:
            application/json:
              example:
                message: Hello, world!
